 language: java

jdk: #have Travis test against oracle and openjdk versions
 - oraclejdk8
 - openjdk8

addons:
  apt:
    packages:
      - oracle-java8-installer #update oracle Java 8 version

install: 
  mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 -DskipTests=true #force travis to use 1.8 version of maven

script: 
  mvn test -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 #force testing with maven 1.8


