--Look up computers donated by one individual.
--Look up specific computer(s) donated to a person or entity.
--Look up all computers signed off by one officer/branch.
--Look up computers where recycled status is true.
--Look up specific computer by serial number.
--Look up specific computer by processor, ram, storage.
--Look up all computer by specific make or model.
--Look up all computers by a specific part installed in it.
--Look up all parts available.
--Look up all parts by part type (storage, ram, optical drive, etc).
--Look up all computers donated by specific date or date range.

--Find all donations.
--Find all donations by date (specific or range), donee, or signed off by officer.
--Find all expenses.
--Find all expenses by date (specific or range), paid to whom, or signed off by officer.
--Calculate all donations by date (specific or range).
--Calculate all expenses by date (specific or range).

--Find all submissions for specific email address.
--Find all donation application (specific date, range of dates, email address).
--Find all applying applications (specific date, range of dates, email address).
